module.exports = {
  INVALID_ID: 'Невалидный id',
  NOT_FOUND: 'Ресурс не найден',
  INVALID_LINK: 'Поле link заполнено не корректно',
  INVALID_IMAGE: 'Поле image заполнено не корректно',
  BAD_REQUEST: 'Некорректный адрес!',
  SERVER_ERROR: 'На сервере произошла ошибка',
  AUTH: 'Доступ запрещен. Необходима авторизация',
  ERROR_EMAIL_PASS: 'Неправильные почта или пароль',
  EMPTY_DATABASE: 'База данных user пуста!',
  NOT_YOUR_ARTICLE: 'Это не ваша статья, не может быть удалена',
  ARTICLE_NOT_FOUND: 'Статья не найдена',
  FAILED_CREATE_USER: 'Такого пользователя нет',
  RATE_LIMIT: 'Слишком много запросов создано с этого IP, пожалуйста, попробуйте еще раз через 15 минут',
};
